=== cabanem/analyze-workato-connector/.out/connector.schema.json
{
  "$id": "https://example.com/workato-connector-ir.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Workato Connector IR",
  "version": "1-0-0",
  "type": "object",
  "required": [
    "root",
    "issues",
    "graph",
    "stats",
    "salvaged"
  ],
  "properties": {
    "root": {
      "$ref": "#/definitions/node"
    },
    "issues": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/issue"
      }
    },
    "graph": {
      "type": "object",
      "properties": {
        "nodes": {
          "type": "object"
        },
        "edges": {
          "type": "array",
          "items": {
            "type": "array"
          }
        }
      }
    },
    "stats": {
      "type": "object"
    },
    "salvaged": {
      "type": "boolean"
    },
    "lambdas": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  },
  "definitions": {
    "loc": {
      "type": "object",
      "properties": {
        "line": {
          "type": "integer"
        },
        "column": {
          "type": "integer"
        },
        "length": {
          "type": "integer"
        },
        "begin": {
          "type": "integer"
        },
        "end": {
          "type": "integer"
        }
      }
    },
    "node": {
      "type": "object",
      "required": [
        "id",
        "kind",
        "name",
        "loc",
        "meta",
        "children"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "loc": {
          "$ref": "#/definitions/loc"
        },
        "meta": {
          "type": "object"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        }
      }
    },
    "issue": {
      "type": "object",
      "properties": {
        "severity": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "loc": {
          "$ref": "#/definitions/loc"
        },
        "context": {
          "type": "object"
        }
      }
    }
  }
}

=== cabanem/analyze-workato-connector/.out/connector.ir.json
{
  "root": {
    "id": "n_00d8addb8c320e6f",
    "kind": "connector",
    "name": "Vertex AI",
    "loc": {
      "line": 1,
      "column": 0,
      "length": 139797,
      "begin": 0,
      "end": 139797
    },
    "meta": {
      "filename": "connector.rb",
      "root_keys": [
        "actions",
        "connection",
        "custom_action",
        "custom_action_help",
        "methods",
        "object_definitions",
        "pick_lists",
        "test",
        "title",
        "triggers",
        "version"
      ],
      "doc": null
    },
    "children": [
      {
        "id": "n_ed4ab15fd71232d6",
        "kind": "connection",
        "name": "connection",
        "loc": {
          "line": 8,
          "column": 14,
          "length": 9433,
          "begin": 191,
          "end": 9624
        },
        "meta": {
          "authorization_type_literal": "multi"
        },
        "children": [

        ]
      },
      {
        "id": "n_46f92993f54caddc",
        "kind": "test",
        "name": "test",
        "loc": {
          "line": 224,
          "column": 8,
          "length": 678,
          "begin": 9637,
          "end": 10315
        },
        "meta": {
        },
        "children": [

        ]
      },
      {
        "id": "n_ee3b8428eaa7274f",
        "kind": "methods",
        "name": "methods",
        "loc": {
          "line": 811,
          "column": 11,
          "length": 95394,
          "begin": 37408,
          "end": 132802
        },
        "meta": {
        },
        "children": [
          {
            "id": "n_735f3339f67e3723",
            "kind": "method",
            "name": "build_payload",
            "loc": {
              "line": 817,
              "column": 19,
              "length": 7330,
              "begin": 37600,
              "end": 44930
            },
            "meta": {
              "args": [
                "template:",
                "variables:",
                "format:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_c6ed6bd8ad0fbcef",
            "kind": "method",
            "name": "enrich_response",
            "loc": {
              "line": 1014,
              "column": 21,
              "length": 1076,
              "begin": 44984,
              "end": 46060
            },
            "meta": {
              "args": [
                "response:",
                "metadata:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_e52c88457cbb1082",
            "kind": "method",
            "name": "extract_response",
            "loc": {
              "line": 1040,
              "column": 22,
              "length": 1179,
              "begin": 46111,
              "end": 47290
            },
            "meta": {
              "args": [
                "data:",
                "path:",
                "format:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_4c55ba39e0f8a2fa",
            "kind": "method",
            "name": "http_request",
            "loc": {
              "line": 1069,
              "column": 18,
              "length": 3959,
              "begin": 47340,
              "end": 51299
            },
            "meta": {
              "args": [
                "connection",
                "method:",
                "url:",
                "payload:",
                "headers:",
                "retry_config:",
                "request_format:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_6fa4e7c38dbc3bf7",
            "kind": "method",
            "name": "transform_data",
            "loc": {
              "line": 1162,
              "column": 20,
              "length": 778,
              "begin": 51348,
              "end": 52126
            },
            "meta": {
              "args": [
                "input:",
                "from_format:",
                "to_format:",
                "connection:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_40d65e2414e179bf",
            "kind": "method",
            "name": "validate_input",
            "loc": {
              "line": 1184,
              "column": 20,
              "length": 4248,
              "begin": 52176,
              "end": 56424
            },
            "meta": {
              "args": [
                "data:",
                "schema:",
                "constraints:"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_a7bb99c191d71eac",
            "kind": "method",
            "name": "with_resilience",
            "loc": {
              "line": 1288,
              "column": 21,
              "length": 2187,
              "begin": 56473,
              "end": 58660
            },
            "meta": {
              "args": [
                "operation:",
                "config:",
                "task:",
                "connection:",
                "blockarg"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_c45bd0d836940af8",
            "kind": "method",
            "name": "execute_pipeline",
            "loc": {
              "line": 1346,
              "column": 22,
              "length": 2915,
              "begin": 58826,
              "end": 61741
            },
            "meta": {
              "args": [
                "connection",
                "operation",
                "input",
                "config"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_08758123084516be",
            "kind": "method",
            "name": "behavior_registry",
            "loc": {
              "line": 1445,
              "column": 23,
              "length": 9985,
              "begin": 61968,
              "end": 71953
            },
            "meta": {
              "args": [

              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_e618b10b6c0d1dfc",
            "kind": "method",
            "name": "configuration_registry",
            "loc": {
              "line": 1702,
              "column": 28,
              "length": 1079,
              "begin": 72036,
              "end": 73115
            },
            "meta": {
              "args": [
                "connection",
                "user_config"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_d264c41acce19399",
            "kind": "method",
            "name": "execute_behavior",
            "loc": {
              "line": 1744,
              "column": 22,
              "length": 2835,
              "begin": 73193,
              "end": 76028
            },
            "meta": {
              "args": [
                "connection",
                "behavior",
                "input",
                "user_config"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_f833a200fc51f529",
            "kind": "method",
            "name": "add_upsert_ack",
            "loc": {
              "line": 1815,
              "column": 20,
              "length": 304,
              "begin": 76213,
              "end": 76517
            },
            "meta": {
              "args": [
                "response",
                "input"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_bfd076c154d47a15",
            "kind": "method",
            "name": "add_word_count",
            "loc": {
              "line": 1825,
              "column": 20,
              "length": 290,
              "begin": 76540,
              "end": 76830
            },
            "meta": {
              "args": [
                "response",
                "input"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_8c827b6edaebcdbb",
            "kind": "method",
            "name": "apply_template",
            "loc": {
              "line": 1840,
              "column": 20,
              "length": 238,
              "begin": 76884,
              "end": 77122
            },
            "meta": {
              "args": [
                "template",
                "variables"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_9d13fc2bf8078032",
            "kind": "method",
            "name": "approx_token_count",
            "loc": {
              "line": 1851,
              "column": 24,
              "length": 107,
              "begin": 77184,
              "end": 77291
            },
            "meta": {
              "args": [
                "text"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_925548b6f4bc6f8c",
            "kind": "method",
            "name": "augment_vector_context",
            "loc": {
              "line": 1856,
              "column": 28,
              "length": 711,
              "begin": 77322,
              "end": 78033
            },
            "meta": {
              "args": [
                "connection",
                "local_input"
              ]
            },
            "children": [

            ]
          },
          {
            "id": "n_17c58a6a0852b6b7",
            "kind": "method",
            "name": "build_endpoint_url",
            "loc": {
              "line": 1876,
              "column": 24,
              "length": 3050,
